# Generated by Django 5.2.6 on 2025-09-07 21:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('room_password', models.CharField(blank=True, max_length=50)),
                ('moderator_name', models.CharField(default='Facilitator', max_length=100)),
                ('max_participants', models.IntegerField(default=20)),
                ('enable_lobby', models.BooleanField(default=True)),
                ('enable_recording', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('participant_count', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jitsi_rooms', to='circles.circle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('participant', 'Participant')], max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('speak_time', models.DurationField(default=datetime.timedelta)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='jitsi_rooms.jitsiroom')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jitsiroom',
            index=models.Index(fields=['circle', 'status'], name='jitsi_rooms_circle__861be3_idx'),
        ),
        migrations.AddIndex(
            model_name='jitsiroom',
            index=models.Index(fields=['room_name'], name='jitsi_rooms_room_na_b3ae99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together={('room', 'participant_id')},
        ),
    ]
