# Generated by Django 5.2.6 on 2025-10-28 00:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to JSON file (relative or absolute)', max_length=512)),
                ('language', models.CharField(help_text="Target language (e.g., 'thai', 'vietnamese')", max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('loaded', 'Loaded into DB'), ('in_session', 'Active Session'), ('saved', 'Saved to JSON'), ('archived', 'Archived')], default='uploaded', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('json_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_loaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_documents', to='circles.circle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to='authentication.accesskey')),
            ],
            options={
                'verbose_name': 'Translation Document',
                'verbose_name_plural': 'Translation Documents',
                'unique_together': {('circle', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='TranslationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_paragraphs', models.IntegerField(default=0)),
                ('paragraphs_modified', models.IntegerField(default=0)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_sessions', to='circles.circle')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='translation.translationdocument')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_sessions', to='authentication.accesskey')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_sessions', to='authentication.accesskey')),
            ],
            options={
                'verbose_name': 'Translation Session',
                'verbose_name_plural': 'Translation Sessions',
            },
        ),
        migrations.CreateModel(
            name='ParagraphCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.CharField(help_text="Paragraph ID from JSON (e.g., 'p9-1')", max_length=50)),
                ('chapter_id', models.CharField(blank=True, max_length=50)),
                ('section_id', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField(help_text='Original English text (read-only)')),
                ('original_translation', models.TextField(help_text='AI-generated translation from JSON (read-only)')),
                ('corrected_translation', models.TextField(help_text='Human-corrected translation (editable)')),
                ('status', models.CharField(choices=[('unchecked', 'Unchecked'), ('in_progress', 'In Progress'), ('approved', 'Approved')], default='unchecked', max_length=20)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_paragraphs', to='authentication.accesskey')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraph_edits', to='authentication.accesskey')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='translation.translationsession')),
            ],
            options={
                'verbose_name': 'Paragraph Correction',
                'verbose_name_plural': 'Paragraph Corrections',
                'ordering': ['paragraph_id'],
                'unique_together': {('session', 'paragraph_id')},
            },
        ),
    ]
