# Generated by Django 5.2.6 on 2025-09-07 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('jitsi_room_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('ended', 'Ended')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('facilitator_key', models.ForeignKey(limit_choices_to={'role': 'facilitator'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.accesskey')),
            ],
            options={
                'verbose_name': 'Circle',
                'verbose_name_plural': 'Circles',
            },
        ),
        migrations.CreateModel(
            name='CircleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_connected', models.BooleanField(default=True)),
                ('access_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.accesskey')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='circles.circle')),
            ],
            options={
                'verbose_name': 'Circle Participant',
                'verbose_name_plural': 'Circle Participants',
                'unique_together': {('circle', 'access_key')},
            },
        ),
    ]
