# Generated by Django 5.2.6 on 2025-10-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='circle_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('translation', 'Translation'), ('study', 'Study')], default='discussion', max_length=20),
        ),
    ]
